name: SwiftRuntimeKitDemo
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
packages:
  SwiftRuntimeKit:
    path: ../
targets:
  SwiftRuntimeKitDemo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.SwiftRuntimeKitDemo
      INFOPLIST_FILE: Info.plist
    dependencies:
      - package: SwiftRuntimeKit
