name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build (SwiftPM)
        run: swift build -v
      - name: Test (SwiftPM)
        run: swift test -v
